- src/milkyplay/drivers/osx/AudioDriver_COREAUDIO.cpp
- src/milkyplay/drivers/osx/AudioDriver_COREAUDIO.h
Also removed old-fashioned 'register' keywords; the compiler will
probably do a better job. Some whitespace tidied.
> CoreAudio: Support devices with >2 channels per frame

- platforms/osx/milkytracker_cocoa/Info.plist
- platforms/osx/milkytracker_cocoa/milkytracker_cocoa.xcodeproj/project.pbxproj
- resources/pictures/docicons/osx/genicons.py
A Python script in resources/pictures/docicons/osx called 'genicons.py' must be run to generate the icons before building the Cocoa project with Xcode.
See script comments for instructions/requirements.
> Cocoa: Add custom document icons for supported filetypes

- src/tracker/EnvelopeEditorControl.cpp
- src/tracker/EnvelopeEditorControl.h
- src/tracker/SampleEditorControl.cpp
- src/tracker/SampleEditorControl.h
- src/tracker/SectionSettings.cpp
- src/tracker/TrackerSettings.cpp
After reading Raina's enhancement request (Issue #48), I realized that this is also a feature that I've wanted for many years so I can re-use muscle memory used on other Windows programs.  I went ahead and implemented it in a fork.
Changes:
1)  Added horizontal scroll to the envelope and sample editors, via SHIFT+Mousewheel.  I chose SHIFT as the modifier because this is a common shortcut for horizontal scroll used in many other programs.  This appears to work fine.  My only concern is that the scroll increment seems a little small in the instrument editor (i.e. you have to roll the wheel a lot to get it to scroll a reasonable distance).  I left it alone because I wanted to stay consistent with the existing horizontal scroll feature, for those with horizontal mousewheels on their mice. …
> Patch for Issue #48

- appveyor.yml
Ties in with #73; we may as well make the continuous integration build with the XP toolset.
> AppVeyor: Compile with XP-compatible toolset

- src/tracker/cocoa/MTKeyTranslator.mm
This is a quick and simple fix, but not a hack, so there's no reason why it can't be used in the long term as the proper fix for OSX, but see notes below.
Since Mac doesn't have an INSERT key (and Cocoa doesn't have the concept of one, so it can't be simulated either) we need a key on Mac for INSERT. F13 is above the fn key on a full size Mac keyboard (fn is above delete, where Ins is on standard non-Mac keyboards), so seems an obvious choice. However, the compact (laptop and Bluetooth) keyboards don't have an F13, so this is only a partial fix. It is possible to simulate any key on Mac easily enough with an Automator script and a system-preferences keyboard shortcut, so F13 can be simulated in OSX for those without a full-size keyboard.
TODO: Update manual to reflect the key to use for …
> Fixes #96 : Map F13 to the INSERT virtual key on OSX.

- docs/CMakeLists.txt
- src/tracker/TrackerStartUp.cpp
```
TrackerStartUp.cpp:129:12: error: call to 'abs' is ambiguous
deltaT = abs(::PPGetTickCount() - startTime);
^~~
```
This is because PPGetTickCount() returns an unsigned value, and it is therefore ambiguous to which type the expression should be casted before calling abs(). A similar ambiguity exists further down in the cpp file.  Fix these by explicity casting the PPGetTickCount() return value to a signed type.
This bug was originally reported in the [FreeBSD bugtracker](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=208489).
> Fix a compiler error with with libc++ 3.8.0

- src/milkyplay/ExporterXM.cpp
- src/milkyplay/LoaderMOD.cpp
Currently MilkyTracker simply bails out when trying to write a MOD file with more than 32 channels, leaving behind an incomplete file on disk. I have extended the logic to deal with any amount of channels that can be dealt with using the classic "xxCH" magic bytes (up to 99, same code as in OpenMPT).
In addition, M!K! magic bytes are written for 4-channel MODs with more than 64 patterns rather than M.K. as ProTracker might otherwise not load the file properly.
It would be nice to have show warning when trying to save a MOD with more than 99 channels, but that is outside the scope of this pull request (so the incomplete file is still being written in that case).
> MOD loading/saving up to 99 channels, and set M!K! magic bytes

- .gitignore
Tested by building, running `git status` to see the files,
adding the `.gitignore` file, verifying that `git status`
shows no changes.
> Fix #124: Add gitignore folder for generated build output

- cmake/FindRTMIDI.cmake
On Fedora detection, the RtMidi header has no "// Version:" string.
So, I used the #define RTMIDI_VERSION string instead.
> fix rtmidi version extraction

- src/milkyplay/ExporterXM.cpp
WFx command in IT is not handled correctly, always reducing the volume by 15 rather than the provided value.
> Fix fine global volume slide down handling

- src/ppui/sdl/DisplayDeviceFB_SDL.cpp
- src/ppui/sdl/DisplayDevice_SDL.cpp
- src/ppui/sdl/DisplayDevice_SDL.h
Try to init SDL2 to always default to OpenGL ES2, as this is supported by most Platforms i.e (MacOS, Windows, Android, Linux, Linux on Single Board Computers like RPi or ODROID
Get faster drawings and better Platform compatibility, as OpenGL ES2 is a subset of OpenGL, nowadays all GPU driver support OpenGL ES2 too but not all OpenGL ES2 capable device support OpenGL ( i.e SBC's ), if the GPU driver is somewhat old than it will fallback (create renderer with -1 driver index) to the first supported renderer which is probably OpenGL 1.0 or 1.1, in worst case it is a software renderer but this is only on very old hardware the case.
SBC's like ODROID XU4 and N1
but it should work on: all Windows, MacOS, Android, Linux and Unix like OS if they too build a SDL2 version of MilkyTracker
> Add: better plaform compatibility, default to OpenGL ES2 renderer

- src/milkyplay/drivers/jack/AudioDriver_JACK.cpp
On a Debian system where the jack developer package is not installed, "libjack.so" is not available but "libjack.so.0" is.
notify @trebmuh
> Try to load JACK with multiple lib names

- src/tracker/sdl/SDL_Main.cpp
This fixes #57 sending the absolute path of the command line filename argument.
However, being a novice in C++, I don't know if this is a cross operating system solution.
May someone help me with that?
Best
> Send the absolute path of the file so the save location is preserved

- src/milkyplay/LoaderCBA.cpp
Fixes: https://github.com/milkytracker/MilkyTracker/issues/196
Converts the panning effect range from 0-128 to 0-255 for CBA files.
> Fix: Convert CBA panning values

- src/tracker/SampleEditorControlToolHandler.cpp
Putting a quarter period (0.25) of basic wave forms is
useful for autogenerating envelopes for various filters
(Amplitude, Phase, Frequence, Flanger)
But the UI field only allowed 1 digit after decimal point, making that
impossible.
Sensible maximum value is maximum length of sample/2 to fill with
waveform at Nyquist frequency.
Maximum length for a sample in the same UI description file is 1024 * 1024 * 10 -1
so that would be 1024 * 1024 * 5
> Allow specifying a quarter period (0.25) for periods in generator

- src/milkyplay/ChannelMixer.cpp
- src/milkyplay/PlayerGeneric.cpp
- src/milkyplay/drivers/sdl/AudioDriver_SDL.cpp
- src/milkyplay/drivers/sdl/AudioDriver_SDL.h
Hi! I've been trying to use milkyplay as a library and ran into several issues. I put together a minimal example using SDL2:
```cpp
#include "SDL.h"
#include "MilkyPlay.h" 
#include "AudioDriver_SDL.h"
int main(int argc, char *argv[]) {
SDL_Init(SDL_INIT_EVERYTHING);
SDL_Window *window = SDL_CreateWindow(
"MilkyPlay Test",
SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED,
800, 480, SDL_WINDOW_SHOWN
);
SDL_Renderer *renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_SOFTWARE);
AudioDriver_SDL driver;
PlayerGeneric player(44100, &driver);
XModule mod;
if (mod.loadModule("Goodboy4.xm") != MP_OK) {
printf("Could not open .xm file.\n");
return 1;
}
if (player.startPlaying(&mod) != MP_OK) {
printf("Failed to start playing!\n");
return 1;
}
while (true) {
SDL_Event e;
while …
```
> Fix some milkyplay bugs/crashes

- src/tracker/win32/Win32_resources.rc
See https://stackoverflow.com/q/3566018/2038264 and https://stackoverflow.com/q/37913963/2038264
`afxres.h` is an MFC header, which can be replaced with `windows.h` if the user doesn't have MFC.
> Fix windows build for non-MFC

- src/milkyplay/LoaderS3M.cpp
MilkyTracker is dividing units for 16-bit samples by two during S3M import, which leads to only half of the data being loaded (since S3M uses units of samples, not bytes). This patch fixes that.
> Fix for 16-bit samples in S3M importer

- src/ppui/Menu.h
- src/tracker/SampleEditor.cpp
- src/tracker/SampleEditor.h
- src/tracker/SampleEditorControl.cpp
- src/tracker/SampleEditorControl.h
Added a right click menu option to the sample editor that sets the loop  to the selection range as requested in #107.
It sets the loop type to Forward if there's no other loop type, and uses the existing loop type if set (unless loop type is One shot and the selection start isn't at the very beginning, similar to dragging the start loop point).
> Add #107 Feature Request "set loop to selection"

- src/tracker/SampleEditor.cpp
- src/tracker/SampleEditor.h
- src/tracker/SampleEditorControl.cpp
- src/tracker/SampleEditorControl.h
This allows for various usecases:
* deadsimple param-less way to tame dynamics, louder vocals, expand the dynamic range
* apply tube-like/soft-clipping distortion
* use 'redo filter' to intensify the effect (further)
> added quick and dirty dynamic compression

- docs/MilkyTracker.html
- src/tracker/ModuleEditor.h
- src/tracker/SampleEditorControl.cpp
- src/tracker/SampleEditorControl.h
- src/tracker/SectionSamples.cpp
- src/tracker/Tracker.h
- src/tracker/TrackerKeyboard.cpp
What does it do?
* open the sample editor
* hit **CTRL-SHIFT-V** to 'sample' the current pattern into the waveform editor
* OR just rightclick "ext.paste" -> "capture pattern"
This commit serves various usecases:
* sounddesign: create new samples by combining samples in a pattern (kick/snare-layering e.g.)
* visualize & analyze the dynamics of your mixdown (spot phase issues e.g.)
* reduce mouse-menu-diving using disk.op->set wav->set order->currentsample and so on
* this is a lowhanging fruit since there were many requests for visualizing the mix (spectrum e.g.)
> easily 'sample' current pattern into current sample

- src/tracker/DialogResample.cpp
- src/tracker/DialogResample.h
- src/tracker/ModuleEditor.cpp
- src/tracker/ModuleEditor.h
- src/tracker/SampleEditor.cpp
- src/tracker/SampleEditor.h
- src/tracker/SampleEditorControlLastValues.h
- src/tracker/SampleEditorControlToolHandler.cpp
Allows that all 9xx commands affected by a resampling operation are computationally adjusted automatically. While the sample operation can be undone, the 9xx change can unfortunately not be undone, because there is no undo stack on entire song operations.
> Feature: Add 9xx adjustment option to sample resampler

- src/tracker/SectionSamples.cpp
This allows it to compile with the `__LOWRES__` flag set, which was broken by 075d32ec2662cbbf52caf45e1ec97a2df3254248
> Fix missing argument to SampleEditorControl

- src/tracker/sdl/SDL_Main.cpp
quick and dirty fix to issue where milkytracker did not check for the presence of a file before attempting to load it (for example, when doing `milkytracker ''`)
> fix segfault when passing invalid filename on command line

- src/fx/TexturedGrid.cpp
- src/fx/TexturedGrid.h
- src/ppui/BasicTypes.h
- src/ppui/ListBox.cpp
- src/tracker/AnimatedFXControl.cpp
- src/tracker/AnimatedFXControl.h
- src/tracker/PatternEditorControl.cpp
- src/tracker/PatternEditorControl.h
- src/tracker/PatternTools.h
- src/tracker/PianoControl.cpp
I moved as much initialization as I could from constructor bodies into initializer lists, because I feel it's easier to track a single list of field initializers, than having to read two separate lists to see if a given field is initialized. I'm not sure if this was the best decision, because long initializer lists are ugly.
I ran MilkyTracker in ubsan, and found invalid bool accesses in these two structs. I initialized all fields I could find (though I might've missed some), instead of looking through control flow to see which fields were used or not. I don't like fields like `PatternEditorControl::visibleWidth` which are uninitialized until you call a method like `PatternEditorControl::setSize()` to set them, meaning the class isn't safe to use after the constructor, but only safe after …
> Fix uninitialized memory being used

- src/ppui/DialogFileSelector.cpp
The width/height was hardcoded, and on a 22" screen this is quite claustrophobic.
This fix (see screenshot) will make it adapt to the screensize.
This is nice especially since samplepacks can be huge, and personal sample/instrument-directories can grow over time.
It caps to max 500x800 to prevent useless width-margins (or data overload in case of height) and still looks good on the smallest resolution:
> responsive filedialog

- src/tracker/SampleEditor.cpp
- src/tracker/SampleEditor.h
- src/tracker/SampleEditorControl.cpp
- src/tracker/SampleEditorControl.h
**Issue:** the default 'Paste > Mix' spreads the selection over the destination sample.
> This is fine, but a bit unexpected compared the normal wave-editor 'mix paste'
**Solution:** 'Paste > Mix' has been renamed to 'Paste > Mix spread' and introduced are:
* Paste > Mix (mix without spreading/stretching)
* Paste > Mix overflow (if the clipboard duration is longer, then it folds back into the beginning pacman-style)
> sampleeditor: improved paste (mix, mix overflow, spread)

- src/milkyplay/PlayerBase.h
initialise ticker to 0
on the first run, ticker points to uninit memory. the left shift in
TimeRecord constructor by 8 makes it overflow past the left which is UB.
(i'm not 100% sure about this, but it makes ubsan happy)
---
i was hunting down a crash on start of the latest release, and found it to be fixed by
https://github.com/milkytracker/MilkyTracker/commit/7e9171488fc47ad2de646a4536794fda21e7303d , after i found it myself too.
in the process i found more easy UB via ubsan, so i fixed that too.
for reference:
ticker 0:
```
(lldb) bt
* thread #1, name = 'milkytracker', stop reason = Invalid shift base
* frame #0: 0x0000555555ce48b0 milkytracker`__ubsan_on_report at ubsan_monitor.cpp:39:40
frame #1: 0x0000555555cdf559 milkytracker`::~Diag() at ubsan_diag.cpp:352:29
frame #2: …
```
> fix some UB

- CMakeLists.txt
To help with reproducible builds[1] the `string(TIMESTAMP)` CMake function respects `$SOURCE_DATE_EPOCH` if set and uses that instead of the current time. However, the output is still sensitive to the local timezone which is enough to make the build un-reproducible.
Fix this by using UTC when getting the timestamp.
[1] https://reproducible-builds.org/
> Use UTC when writing metainfo timestamp
